### ISSUE TITLE
New Meteor.method: createNewPet

### ISSUE THREAD

**Issue by msolters** [msolters/woofi#14]
```
_pet:
  name: "pet's name"
  type: "dog" || "cat"
  owner: [Meteor.userId() of owner]
```
